# Generated by Django 2.1.4 on 2018-12-30 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='blue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='house_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
