# Generated by Django 2.1 on 2018-12-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smz',
            old_name='C_tele',
            new_name='c_tele',
        ),
    ]
